//////////////////////////////////////////////////////////////////////////////
// Name:        SVGPointList.cpp
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by genList.py
//////////////////////////////////////////////////////////////////////////////

#include "SVGPointList.h"
#include <wx/tokenzr.h>
#include <wx/arrimpl.cpp>
WX_DEFINE_OBJARRAY(wxSVGPointListBase);

wxString wxSVGPointList::GetValueAsString() const {
	wxString value;
	for (int i = 0; i < (int) GetCount(); i++) {
		if (i > 0) {
			value += wxT(" ");
		}
		value += wxString::Format(wxT("%g,%g"), Item(i).GetX(), Item(i).GetY());
	}
	return value;
}

void wxSVGPointList::SetValueAsString(const wxString& value) {
	Clear();
	double x, y;
	bool isLast = false; // false => y, true => x
	wxStringTokenizer tkz(value, wxT(" \t\r\n"));
	while (tkz.HasMoreTokens()) {
		wxString token = tkz.GetNextToken().Strip(wxString::both);
		if (token.length() && token.Find(wxT(',')) > 0)
		{
			token.BeforeFirst(wxT(',')).ToCDouble(&x);
			token.AfterFirst(wxT(',')).ToCDouble(&y);
			Add(wxSVGPoint(x, y));
			isLast = false;
		}
		else if (token.length())
		{
			if (isLast)
			{
				token.ToCDouble(&y);
				Last().SetY(y);
				isLast = false;
			}
			else
			{
				token.ToCDouble(&x);
				Add(wxSVGPoint(x, 0));
				isLast = true;
			}
		}
	}
}
